#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x687393EE37D128F8 (matthieu@herrb.eu)
#
Name     : libXfont
Version  : 1.5.4
Release  : 13
URL      : https://www.x.org/releases/individual/lib/libXfont-1.5.4.tar.bz2
Source0  : https://www.x.org/releases/individual/lib/libXfont-1.5.4.tar.bz2
Source99 : https://www.x.org/releases/individual/lib/libXfont-1.5.4.tar.bz2.sig
Summary  : X font Library
Group    : Development/Tools
License  : ICU
Requires: libXfont-lib = %{version}-%{release}
Requires: libXfont-license = %{version}-%{release}
BuildRequires : pkgconfig(fontenc)
BuildRequires : pkgconfig(fontsproto)
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)
BuildRequires : pkgconfig(xtrans)
BuildRequires : xmlto

%description
libXfont provides the core of the legacy X11 font system, handling the
index files (fonts.dir, fonts.alias, fonts.scale), the various font file
formats, and rasterizing them.   It is used by the X servers, the
X Font Server (xfs), and some font utilities (bdftopcf for instance),
but should not be used by normal X11 clients.  X11 clients access fonts
via either the new API's in libXft, or the legacy API's in libX11.

%package dev
Summary: dev components for the libXfont package.
Group: Development
Requires: libXfont-lib = %{version}-%{release}
Provides: libXfont-devel = %{version}-%{release}
Requires: libXfont = %{version}-%{release}

%description dev
dev components for the libXfont package.


%package lib
Summary: lib components for the libXfont package.
Group: Libraries
Requires: libXfont-license = %{version}-%{release}

%description lib
lib components for the libXfont package.


%package license
Summary: license components for the libXfont package.
Group: Default

%description license
license components for the libXfont package.


%prep
%setup -q -n libXfont-1.5.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559787211
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1559787211
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libXfont
cp COPYING %{buildroot}/usr/share/package-licenses/libXfont/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/fonts/bdfint.h
/usr/include/X11/fonts/bitmap.h
/usr/include/X11/fonts/bufio.h
/usr/include/X11/fonts/fntfil.h
/usr/include/X11/fonts/fntfilio.h
/usr/include/X11/fonts/fntfilst.h
/usr/include/X11/fonts/fontconf.h
/usr/include/X11/fonts/fontencc.h
/usr/include/X11/fonts/fontmisc.h
/usr/include/X11/fonts/fontshow.h
/usr/include/X11/fonts/fontutil.h
/usr/include/X11/fonts/fontxlfd.h
/usr/include/X11/fonts/ft.h
/usr/include/X11/fonts/ftfuncs.h
/usr/include/X11/fonts/pcf.h
/usr/lib64/libXfont.so
/usr/lib64/pkgconfig/xfont.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXfont.so.1
/usr/lib64/libXfont.so.1.4.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libXfont/COPYING
